- hosts: ctrl
  become: yes
  vars:
    controller_ip: "192.168.56.100"

  tasks:

    # STEP 13 — kubeadm init
    - name: Check if Kubernetes already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_conf

    - name: Initialize Kubernetes control-plane
      shell: >
        kubeadm init
        --apiserver-advertise-address={{ controller_ip }}
        --node-name={{ inventory_hostname }}
        --pod-network-cidr=10.244.0.0/16
      when: not kubeadm_conf.stat.exists


    # STEP 14 — Configure kubectl for vagrant + export to host
    - name: Create .kube directory for vagrant
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: "0755"
      when: not kubeadm_conf.stat.exists

    - name: Copy admin.conf to vagrant kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: "0644"
        remote_src: true
      when: not kubeadm_conf.stat.exists


    - name: Export admin.conf to host machine
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /vagrant/admin.conf
      when: not kubeadm_conf.stat.exists

    # STEP 15 — Apply Flannel CNI
    - name: Install Flannel CNI
      command: kubectl apply -f /vagrant/templates/flannel.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      when: not kubeadm_conf.stat.exists
