---
- name: Add SSH keys for Vagrant user
  hosts: all
  gather_facts: false
  become: true
  vars:
    ssh_key_dir: "{{ playbook_dir }}/ssh-keys"
    ssh_key_files: "{{ lookup('fileglob', ssh_key_dir + '/*.pub', wantlist=True) }}"

  tasks:
    - name: Add my personal SSH key
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Add all public keys from ssh_keys folder
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ ssh_key_files }}"

    - name: Disable swap immediately
      ansible.builtin.shell: swapoff -a

    - name: Remove swap from fstab to prevent remount on boot
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^\s*[^#].*\sswap\s'
        state: absent

    - name: Ensure overlay and br_netfilter modules are loaded on boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Load br_netfilter module now
      ansible.builtin.modprobe:
        name: br_netfilter
        state: present

    - name: Load overlay module now
      ansible.builtin.modprobe:
        name: overlay
        state: present

    - name: Configure sysctl params for Kubernetes networking
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl parameters
      ansible.builtin.command: sysctl --system

    - name: Deploy /etc/hosts using template
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/hosts.j2"
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

