---
- name: Add SSH keys for Vagrant user
  hosts: all
  gather_facts: false

  vars:
    ssh_key_dir: "{{ playbook_dir }}/ssh-keys"
    ssh_key_files: "{{ lookup('fileglob', ssh_key_dir + '/*.pub', wantlist=True) }}"

  tasks:
    - name: Add my personal SSH key
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Add all public keys from ssh_keys folder
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ ssh_key_files }}"
