apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.app.name }}
  labels:
    app: {{ .Values.labels.app.app }}
    component: {{ .Values.labels.app.component }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    pp: {{ .Values.labels.app.app }}
    component: {{ .Values.labels.app.component }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}