apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: sms-checker-dr
spec:
  host: app-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user-session
          ttl: 3600s
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2