apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-app-dr
  labels:
    app: {{ .Values.labels.app.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  host: {{ .Values.service.app.name }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user-session
          ttl: 3600s
    connectionPool:
      http:
        http1MaxPendingRequests: 1024
        maxRequestsPerConnection: 1024
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
