apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.labels.app.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  SMTP_USER: {{ .Values.secret.smtpUser | quote }}
  SMTP_PASS: {{ .Values.secret.smtpPass | quote }}