apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.labels.app.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  SLACK_WORKFLOW_URL: {{ .Values.secret.slackWorkflowUrl | quote }}