apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sms-checker-vs
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.istio.gateway.name }}
  http:
    - match:
        - headers:
            testing:
              exact: "true"  
      route:
        - destination:
            host: app-service
            subset: v2
          weight: 100
    - route:
        - destination:
            host: app-service
            subset: v1
          weight: 100