# kube-flannel.yaml (modified for host-only network eth1)

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-flannel-ds
  namespace: kube-flannel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: flannel

---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-flannel

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-flannel
  labels:
    app: flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        app: flannel
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: kube-flannel
        image: quay.io/flannel/flannel:v0.26.7
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        - --iface=eth1
        volumeMounts:
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      initContainers:
      - name: install-cni
        image: quay.io/flannel/flannel:v0.26.7
        command:
        - cp
        - -f
        - /etc/kube-flannel/cni-conf.json
        - /etc/cni/net.d/10-flannel.conflist
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: flannel-cfg
        configMap:
          name: kube-flannel-cfg

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-flannel-cfg
  namespace: kube-flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
